version: '2'

services:
  lemonldap-app:
    image: registry.selfdesign.org/docker/lemonldap:latest
    container_name: lemonldap-app
    volumes:
    #- ./config:/assets/lsc
    - ./logs/:/www/logs
    - /etc/localtime:/etc/localtime:ro
    environment:
    - VIRTUAL_HOST=sso.tiredofit.ca,manager.sso.tiredofit.ca,reload.sso.tiredofit.ca
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=sso.tiredofit.ca,manager.sso.tiredofit.ca,reload.sso.tiredofit.ca
    - LETSENCRYPT_EMAIL=dave@tiredofit.ca

    - ZABBIX_HOSTNAME=lemonldap-app

    - MANAGER_HOSTNAME=manager.sso.tiredofit.ca
    - PORTAL_HOSTNAME=sso.tiredofit.ca
    - HANDLER=reload.sso.tiredofit.ca
    
    - DB_HOST=lemonldap-db
    - DB_NAME=lemonldap
    - DB_USER=lemonldap
    - DB_PASS=userpassword
    networks:
      - proxy-tier
    restart: always

  lemonldap-db:
    image: registry.selfdesign.org/docker/mariadb
    container_name: lemonldap-db
    volumes:
      - /var/local/db/lemonldap-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lemonldap
      - MYSQL_USER=lemonldap
      - MYSQL_PASSWORD=userpassword

      - ZABBIX_HOSTNAME=lemonldap-db

    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
