version: '2'

services:
  lemonldap-app:
    image: tiredofit/lemonldap:latest
    container_name: lemonldap-app
    volumes:
    - ./conf/:/etc/lemonldap-ng
    - ./logs/:/www/logs
    - /etc/localtime:/etc/localtime:ro
    environment:
    - VIRTUAL_HOST=manager.sso.example.com,sso.example.com,reload.sso.example.com,test.sso.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=manager.sso.example.com,sso.example.com,reload.sso.example.com,test.sso.example.com
    - LETSENCRYPT_EMAIL=email@example.com

    - ZABBIX_HOSTNAME=lemonldap-app

    - DOMAIN_NAME=example.com
    - MANAGER_HOSTNAME=manager.sso.example.com
    - PORTAL_HOSTNAME=sso.example.com
    - RELOAD_HOSTNAME=reload.sso.example.com
    - TEST_HOSTNAME=test.sso.example.com
 

    - CONFIG_TYPE=MYSQL    
    - SESSION_TYPE=MYSQL
    - DB_HOST=lemonldap-db
    - DB_NAME=lemonldap
    - DB_USER=lemonldap
    - DB_PASS=userpassword
    networks:
      - proxy-tier
    restart: always

  lemonldap-db:
    image: tiredofit/mariadb
    container_name: lemonldap-db
    volumes:
      - /var/local/db/lemonldap-db/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lemonldap
      - MYSQL_USER=lemonldap
      - MYSQL_PASSWORD=userpassword

      - ZABBIX_HOSTNAME=lemonldap-db
    networks:
      - proxy-tier
    restart: always

  lemonldap-db-mongo:
    container_name: lemonldap-db-mongo
    image: tiredofit/mongo
    restart: unless-stopped
    volumes:
     - /var/local/db/lemonldap-db/mongo:/data/db
     - ./dbbackup:/dump
    command: mongod --smallfiles
    networks:
      - proxy-tier
    environment:
      - ZABBIX_HOSTNAME=lemonldap-db-mongo

  lemonldap-db-redis:
    image: tiredofit/redis
    container_name: lemonldap-db-redis
    environment:
      - ZABBIX_HOSTNAME=lemonldap-db-redis

    volumes:
      - /var/local/db/lemonldap/redis:/data
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy


