version: '2'

services:
  lemonldap-app:
    image: tiredofit/lemonldap:2.0-latest
    container_name: lemonldap-app
    volumes:
    - ./data/etc/lemonldap-ng:/etc/lemonldap-ng
    - ./data/var/lib/lemonldap-ng/conf:/var/lib/lemonldap-ng/conf
    - ./logs:/www/logs
    #- ./assets/custom:/assets/custom
    environment:
    - VIRTUAL_HOST=sso.example.com,manager.sso.example.com,handler.sso.example.com,test.sso.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=sso.example.com,manager.sso.example.com,handler.sso.example.com,test.sso.example.com
    - LETSENCRYPT_EMAIL=email@example.com

    - ZABBIX_HOSTNAME=lemonldap-app

    - DOMAIN_NAME=example.com
    - MANAGER_HOSTNAME=manager.sso.example.com
    - PORTAL_HOSTNAME=sso.example.com
    - HANDLER_HOSTNAME=handler.sso.example.com
    - TEST_HOSTNAME=test.sso.example.com

    - MODE=MASTER
 
    - CONFIG_TYPE=FILE
    - SESSION_TYPE=FILE
    - HANDLER_CACHE_TYPE=FILE
    networks:
      - proxy-tier
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always


networks:
  proxy-tier:
    external:
      name: nginx-proxy


